[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"  # change to "build" if you're using CRA, or "out" for Next.js static export

[environment]
  NPM_FLAGS = "--legacy-peer-deps"

[dev]
  command = "npm run dev"
  targetPort = 3000
  port = 8888
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
